spring:
   api_user: test
   api_password: test
   application:
      name: spring-rules-processor
   server:
      port: 8080
   data:
      mongodb:
         uri: mongodb+srv://<user>:<password>@<cluster>/<database>?retryWrites=true&w=majority
logging.level:
  com.company: DEBUG