spring:
   api_user: test
   api_password: test
   application:
      name: spring-rules-processor
   server:
      port: 8080
   data:
      mongodb:
         uri: mongodb+srv://admin:admin@cluster0.qfiwo.mongodb.net/db0?retryWrites=true&w=majority
logging.level:
  com.company: DEBUG