import gr.spring.drools.poc.model.PayzyMember;
global gr.spring.drools.poc.model.PayzyMember member;

dialect "mvel"

rule "Checking number of virtual cards" salience -1
 when
  PayzyMember(virtualCardNumber > 2)
 then
  member.setEligibleForOffer(false);
end

rule "Checking number of physical cards" salience 9
 when
  PayzyMember(physicalCardNumber >= 1 || virtualCardNumber > 2)
 then
  member.setEligibleForOffer(true);
end

rule "Checking number of total cards"
 when
  PayzyMember(physicalCardNumber + virtualCardNumber >= 6)
 then
  member.setEligibleForOffer(true);
end
