spring:
   application:
      name: drools-poc
   data:
      mongodb:
         host: localhost
         port: 27017
         username: root
         password: cognity2023
         database: drools-poc
         authentication-database: admin
server:
   port: 8080
   servlet:
      context-path: /drools-poc
management:
   server:
      port: 8090
      base-path: /
logging.level:
  gr.spring.drools.poc: DEBUG
